// Code generated by protoc-gen-go. DO NOT EDIT.
// source: goods.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//商品信息
type GoodsInfo struct {
	//商品编号
	GoodsID int64 `protobuf:"varint,1,opt,name=goodsID,proto3" json:"goodsID,omitempty"`
	//商品数量
	Count int64 `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	//商品单价
	UnitPrice            int64    `protobuf:"varint,3,opt,name=unitPrice,proto3" json:"unitPrice,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GoodsInfo) Reset()         { *m = GoodsInfo{} }
func (m *GoodsInfo) String() string { return proto.CompactTextString(m) }
func (*GoodsInfo) ProtoMessage()    {}
func (*GoodsInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_a30593c5487368b0, []int{0}
}

func (m *GoodsInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GoodsInfo.Unmarshal(m, b)
}
func (m *GoodsInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GoodsInfo.Marshal(b, m, deterministic)
}
func (m *GoodsInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GoodsInfo.Merge(m, src)
}
func (m *GoodsInfo) XXX_Size() int {
	return xxx_messageInfo_GoodsInfo.Size(m)
}
func (m *GoodsInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_GoodsInfo.DiscardUnknown(m)
}

var xxx_messageInfo_GoodsInfo proto.InternalMessageInfo

func (m *GoodsInfo) GetGoodsID() int64 {
	if m != nil {
		return m.GoodsID
	}
	return 0
}

func (m *GoodsInfo) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *GoodsInfo) GetUnitPrice() int64 {
	if m != nil {
		return m.UnitPrice
	}
	return 0
}

//购买商品
type GetGoodsRequest struct {
	GoodsInfos           []*GoodsInfo `protobuf:"bytes,1,rep,name=goodsInfos,proto3" json:"goodsInfos,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetGoodsRequest) Reset()         { *m = GetGoodsRequest{} }
func (m *GetGoodsRequest) String() string { return proto.CompactTextString(m) }
func (*GetGoodsRequest) ProtoMessage()    {}
func (*GetGoodsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_a30593c5487368b0, []int{1}
}

func (m *GetGoodsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGoodsRequest.Unmarshal(m, b)
}
func (m *GetGoodsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGoodsRequest.Marshal(b, m, deterministic)
}
func (m *GetGoodsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGoodsRequest.Merge(m, src)
}
func (m *GetGoodsRequest) XXX_Size() int {
	return xxx_messageInfo_GetGoodsRequest.Size(m)
}
func (m *GetGoodsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGoodsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetGoodsRequest proto.InternalMessageInfo

func (m *GetGoodsRequest) GetGoodsInfos() []*GoodsInfo {
	if m != nil {
		return m.GoodsInfos
	}
	return nil
}

type GetGoodsResponse struct {
	GoodsInfos           []*GoodsInfo `protobuf:"bytes,1,rep,name=goodsInfos,proto3" json:"goodsInfos,omitempty"`
	TotalPrice           int64        `protobuf:"varint,2,opt,name=totalPrice,proto3" json:"totalPrice,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetGoodsResponse) Reset()         { *m = GetGoodsResponse{} }
func (m *GetGoodsResponse) String() string { return proto.CompactTextString(m) }
func (*GetGoodsResponse) ProtoMessage()    {}
func (*GetGoodsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_a30593c5487368b0, []int{2}
}

func (m *GetGoodsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetGoodsResponse.Unmarshal(m, b)
}
func (m *GetGoodsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetGoodsResponse.Marshal(b, m, deterministic)
}
func (m *GetGoodsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetGoodsResponse.Merge(m, src)
}
func (m *GetGoodsResponse) XXX_Size() int {
	return xxx_messageInfo_GetGoodsResponse.Size(m)
}
func (m *GetGoodsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetGoodsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetGoodsResponse proto.InternalMessageInfo

func (m *GetGoodsResponse) GetGoodsInfos() []*GoodsInfo {
	if m != nil {
		return m.GoodsInfos
	}
	return nil
}

func (m *GetGoodsResponse) GetTotalPrice() int64 {
	if m != nil {
		return m.TotalPrice
	}
	return 0
}

func init() {
	proto.RegisterType((*GoodsInfo)(nil), "pb.GoodsInfo")
	proto.RegisterType((*GetGoodsRequest)(nil), "pb.GetGoodsRequest")
	proto.RegisterType((*GetGoodsResponse)(nil), "pb.GetGoodsResponse")
}

func init() { proto.RegisterFile("goods.proto", fileDescriptor_a30593c5487368b0) }

var fileDescriptor_a30593c5487368b0 = []byte{
	// 211 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4e, 0xcf, 0xcf, 0x4f,
	0x29, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x52, 0x8a, 0xe4, 0xe2, 0x74,
	0x07, 0x09, 0x79, 0xe6, 0xa5, 0xe5, 0x0b, 0x49, 0x70, 0xb1, 0x83, 0xe5, 0x3d, 0x5d, 0x24, 0x18,
	0x15, 0x18, 0x35, 0x98, 0x83, 0x60, 0x5c, 0x21, 0x11, 0x2e, 0xd6, 0xe4, 0xfc, 0xd2, 0xbc, 0x12,
	0x09, 0x26, 0xb0, 0x38, 0x84, 0x23, 0x24, 0xc3, 0xc5, 0x59, 0x9a, 0x97, 0x59, 0x12, 0x50, 0x94,
	0x99, 0x9c, 0x2a, 0xc1, 0x0c, 0x96, 0x41, 0x08, 0x28, 0x39, 0x70, 0xf1, 0xbb, 0xa7, 0x96, 0x80,
	0x4d, 0x0f, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11, 0xd2, 0xe5, 0xe2, 0x4a, 0x87, 0xd9, 0x56,
	0x2c, 0xc1, 0xa8, 0xc0, 0xac, 0xc1, 0x6d, 0xc4, 0xab, 0x57, 0x90, 0xa4, 0x07, 0x77, 0x43, 0x10,
	0x92, 0x02, 0xa5, 0x44, 0x2e, 0x01, 0x84, 0x09, 0xc5, 0x05, 0xf9, 0x79, 0xc5, 0xa9, 0x24, 0x1a,
	0x21, 0x24, 0xc7, 0xc5, 0x55, 0x92, 0x5f, 0x92, 0x98, 0x03, 0x71, 0x23, 0xc4, 0xf5, 0x48, 0x22,
	0x46, 0xae, 0x5c, 0x3c, 0x60, 0x8d, 0xc1, 0xa9, 0x45, 0x65, 0x99, 0xc9, 0xa9, 0x42, 0xa6, 0x5c,
	0x1c, 0x30, 0x2b, 0x85, 0x84, 0xc1, 0xc6, 0xa2, 0x7a, 0x41, 0x4a, 0x04, 0x55, 0x10, 0xe2, 0xaa,
	0x24, 0x36, 0x70, 0x88, 0x1a, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0xeb, 0x96, 0x31, 0xbe, 0x60,
	0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GoodsServiceClient is the client API for GoodsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GoodsServiceClient interface {
	//生成购买订单
	GetGoods(ctx context.Context, in *GetGoodsRequest, opts ...grpc.CallOption) (*GetGoodsResponse, error)
}

type goodsServiceClient struct {
	cc *grpc.ClientConn
}

func NewGoodsServiceClient(cc *grpc.ClientConn) GoodsServiceClient {
	return &goodsServiceClient{cc}
}

func (c *goodsServiceClient) GetGoods(ctx context.Context, in *GetGoodsRequest, opts ...grpc.CallOption) (*GetGoodsResponse, error) {
	out := new(GetGoodsResponse)
	err := c.cc.Invoke(ctx, "/pb.GoodsService/GetGoods", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GoodsServiceServer is the server API for GoodsService service.
type GoodsServiceServer interface {
	//生成购买订单
	GetGoods(context.Context, *GetGoodsRequest) (*GetGoodsResponse, error)
}

// UnimplementedGoodsServiceServer can be embedded to have forward compatible implementations.
type UnimplementedGoodsServiceServer struct {
}

func (*UnimplementedGoodsServiceServer) GetGoods(ctx context.Context, req *GetGoodsRequest) (*GetGoodsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetGoods not implemented")
}

func RegisterGoodsServiceServer(s *grpc.Server, srv GoodsServiceServer) {
	s.RegisterService(&_GoodsService_serviceDesc, srv)
}

func _GoodsService_GetGoods_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGoodsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoodsServiceServer).GetGoods(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.GoodsService/GetGoods",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoodsServiceServer).GetGoods(ctx, req.(*GetGoodsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GoodsService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.GoodsService",
	HandlerType: (*GoodsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetGoods",
			Handler:    _GoodsService_GetGoods_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "goods.proto",
}
