// Code generated by protoc-gen-go. DO NOT EDIT.
// source: order.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//创建订单信息
type CreateOrderInfoRequest struct {
	GoodsInfos           []*GoodsInfo `protobuf:"bytes,1,rep,name=goodsInfos,proto3" json:"goodsInfos,omitempty"`
	TotalPrice           int64        `protobuf:"varint,2,opt,name=totalPrice,proto3" json:"totalPrice,omitempty"`
	UserID               int64        `protobuf:"varint,3,opt,name=userID,proto3" json:"userID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CreateOrderInfoRequest) Reset()         { *m = CreateOrderInfoRequest{} }
func (m *CreateOrderInfoRequest) String() string { return proto.CompactTextString(m) }
func (*CreateOrderInfoRequest) ProtoMessage()    {}
func (*CreateOrderInfoRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{0}
}

func (m *CreateOrderInfoRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOrderInfoRequest.Unmarshal(m, b)
}
func (m *CreateOrderInfoRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOrderInfoRequest.Marshal(b, m, deterministic)
}
func (m *CreateOrderInfoRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOrderInfoRequest.Merge(m, src)
}
func (m *CreateOrderInfoRequest) XXX_Size() int {
	return xxx_messageInfo_CreateOrderInfoRequest.Size(m)
}
func (m *CreateOrderInfoRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOrderInfoRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOrderInfoRequest proto.InternalMessageInfo

func (m *CreateOrderInfoRequest) GetGoodsInfos() []*GoodsInfo {
	if m != nil {
		return m.GoodsInfos
	}
	return nil
}

func (m *CreateOrderInfoRequest) GetTotalPrice() int64 {
	if m != nil {
		return m.TotalPrice
	}
	return 0
}

func (m *CreateOrderInfoRequest) GetUserID() int64 {
	if m != nil {
		return m.UserID
	}
	return 0
}

type CreateOrderInfoResponse struct {
	OrderID              int64    `protobuf:"varint,1,opt,name=orderID,proto3" json:"orderID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateOrderInfoResponse) Reset()         { *m = CreateOrderInfoResponse{} }
func (m *CreateOrderInfoResponse) String() string { return proto.CompactTextString(m) }
func (*CreateOrderInfoResponse) ProtoMessage()    {}
func (*CreateOrderInfoResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_cd01338c35d87077, []int{1}
}

func (m *CreateOrderInfoResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateOrderInfoResponse.Unmarshal(m, b)
}
func (m *CreateOrderInfoResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateOrderInfoResponse.Marshal(b, m, deterministic)
}
func (m *CreateOrderInfoResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateOrderInfoResponse.Merge(m, src)
}
func (m *CreateOrderInfoResponse) XXX_Size() int {
	return xxx_messageInfo_CreateOrderInfoResponse.Size(m)
}
func (m *CreateOrderInfoResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateOrderInfoResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateOrderInfoResponse proto.InternalMessageInfo

func (m *CreateOrderInfoResponse) GetOrderID() int64 {
	if m != nil {
		return m.OrderID
	}
	return 0
}

func init() {
	proto.RegisterType((*CreateOrderInfoRequest)(nil), "pb.CreateOrderInfoRequest")
	proto.RegisterType((*CreateOrderInfoResponse)(nil), "pb.CreateOrderInfoResponse")
}

func init() { proto.RegisterFile("order.proto", fileDescriptor_cd01338c35d87077) }

var fileDescriptor_cd01338c35d87077 = []byte{
	// 202 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xce, 0x2f, 0x4a, 0x49,
	0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48, 0x92, 0xe2, 0x4e, 0xcf, 0xcf,
	0x4f, 0x29, 0x86, 0x08, 0x28, 0xd5, 0x73, 0x89, 0x39, 0x17, 0xa5, 0x26, 0x96, 0xa4, 0xfa, 0x83,
	0x54, 0x79, 0xe6, 0xa5, 0xe5, 0x07, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x08, 0xe9, 0x72, 0x71,
	0x81, 0x15, 0x82, 0xc4, 0x8a, 0x25, 0x18, 0x15, 0x98, 0x35, 0xb8, 0x8d, 0x78, 0xf5, 0x0a, 0x92,
	0xf4, 0xdc, 0x61, 0xa2, 0x41, 0x48, 0x0a, 0x84, 0xe4, 0xb8, 0xb8, 0x4a, 0xf2, 0x4b, 0x12, 0x73,
	0x02, 0x8a, 0x32, 0x93, 0x53, 0x25, 0x98, 0x14, 0x18, 0x35, 0x98, 0x83, 0x90, 0x44, 0x84, 0xc4,
	0xb8, 0xd8, 0x4a, 0x8b, 0x53, 0x8b, 0x3c, 0x5d, 0x24, 0x98, 0xc1, 0x72, 0x50, 0x9e, 0x92, 0x31,
	0x97, 0x38, 0x86, 0x03, 0x8a, 0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0x85, 0x24, 0xb8, 0xd8, 0xc1, 0x6e,
	0xf7, 0x74, 0x91, 0x60, 0x04, 0xeb, 0x81, 0x71, 0x8d, 0xc2, 0xb8, 0x78, 0xc0, 0xca, 0x83, 0x53,
	0x8b, 0xca, 0x40, 0x86, 0xbb, 0x71, 0x71, 0x23, 0x19, 0x22, 0x24, 0x05, 0x72, 0x26, 0x76, 0x6f,
	0x49, 0x49, 0x63, 0x95, 0x83, 0xd8, 0x98, 0xc4, 0x06, 0x0e, 0x14, 0x63, 0x40, 0x00, 0x00, 0x00,
	0xff, 0xff, 0xdc, 0xa3, 0xe0, 0xf6, 0x34, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// OrderServiceClient is the client API for OrderService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OrderServiceClient interface {
	//创建订单
	CreateOrder(ctx context.Context, in *CreateOrderInfoRequest, opts ...grpc.CallOption) (*CreateOrderInfoResponse, error)
}

type orderServiceClient struct {
	cc *grpc.ClientConn
}

func NewOrderServiceClient(cc *grpc.ClientConn) OrderServiceClient {
	return &orderServiceClient{cc}
}

func (c *orderServiceClient) CreateOrder(ctx context.Context, in *CreateOrderInfoRequest, opts ...grpc.CallOption) (*CreateOrderInfoResponse, error) {
	out := new(CreateOrderInfoResponse)
	err := c.cc.Invoke(ctx, "/pb.OrderService/CreateOrder", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OrderServiceServer is the server API for OrderService service.
type OrderServiceServer interface {
	//创建订单
	CreateOrder(context.Context, *CreateOrderInfoRequest) (*CreateOrderInfoResponse, error)
}

// UnimplementedOrderServiceServer can be embedded to have forward compatible implementations.
type UnimplementedOrderServiceServer struct {
}

func (*UnimplementedOrderServiceServer) CreateOrder(ctx context.Context, req *CreateOrderInfoRequest) (*CreateOrderInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOrder not implemented")
}

func RegisterOrderServiceServer(s *grpc.Server, srv OrderServiceServer) {
	s.RegisterService(&_OrderService_serviceDesc, srv)
}

func _OrderService_CreateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrderInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrderServiceServer).CreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.OrderService/CreateOrder",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrderServiceServer).CreateOrder(ctx, req.(*CreateOrderInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _OrderService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.OrderService",
	HandlerType: (*OrderServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateOrder",
			Handler:    _OrderService_CreateOrder_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "order.proto",
}
